#!/usr/bin/env python

from Bio.PDB.PDBParser import PDBParser
from Bio.SeqUtils import IUPACData
import sys
import getopt


def usage():
  print >>sys.stderr, 'Usage: pdbToChain <file_path>'


def residue_to1_letter_aa(residue):
  aa_list = IUPACData.protein_letters_3to1_extended
  normalized_residue_code = residue.resname.title()

  if normalized_residue_code in aa_list:
    return aa_list[normalized_residue_code]    

def main():

  try:
    options, args = getopt.getopt(sys.argv[1:], [])
  except getopt.GetoptError, err:
      print >>sys.stderr, str(err)
      sys.exit(2)

  structure_id = "temp"
  file_path = args[0]

  parser = PDBParser()
  structure = parser.get_structure(structure_id, file_path)

  for model in structure:
    for residue in model.get_residues():    
      aa = residue_to1_letter_aa(residue)
      if (aa is not None):
        print aa

      
if __name__ == '__main__':
  main()
