#!/usr/bin/env python

from PeptideBuilder import *
import sys
import Bio.PDB

def usage():
  print >>sys.stderr, 'Usage: peptideSim <aa_list>'

def main():
  chain = []
  for aa in sys.stdin:
    chain.append(aa.strip())


  prime = chain[0]
  chain.pop(0)

  geo = Geometry.geometry(prime)
  geo.phi=-90
  geo.psi_im1=-40
  structure = PeptideBuilder.initialize_res(geo)

  for aa in chain:
    geo = Geometry.geometry(aa)
    structure = PeptideBuilder.add_residue(structure, geo, -120, 140, -370)
      
  out = Bio.PDB.PDBIO()
  out.set_structure(structure)
  out.save(sys.stdout)

if __name__ == '__main__':
  main()